-- ================================================================
-- STACKWEB — Audit Fixes Migration
-- Run this in the Supabase SQL Editor AFTER the main schema.sql
-- Generated by the deep system audit (June 2026)
-- ================================================================

-- ── Fix 1: Add missing settings columns ──────────────────────
-- The settings UI had toggles for these but the columns didn't exist.
ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS school_motto  TEXT,
  ADD COLUMN IF NOT EXISTS show_bios     BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_photos   BOOLEAN DEFAULT TRUE;

-- ── Fix 2: Fix candidates RLS ────────────────────────────────
-- The old policy allowed ANY Supabase-authenticated user to manage
-- all candidates (insert, update, delete). Replace with admin-only.
DROP POLICY IF EXISTS "Auth users manage candidates" ON candidates;
CREATE POLICY "Admins manage candidates" ON candidates
  FOR ALL
  USING    (is_admin())
  WITH CHECK (is_admin());

-- Keep the existing public read policy for the voter ballot
-- (already correct — filters by is_active = TRUE and active/closed election)
-- DROP POLICY IF EXISTS "Public read candidates" ON candidates; -- do NOT drop this

-- ── Fix 3: Tighten voters public read policy ─────────────────
-- The old policy was USING (TRUE) which exposed ALL voter token rows
-- to any anonymous requester. Restrict to non-revoked status.
DROP POLICY IF EXISTS "Anyone read by token" ON voters;
CREATE POLICY "Public read active voters" ON voters
  FOR SELECT
  USING (status != 'revoked');

-- ── Fix 4: Ensure get_elections_for_tokens() is accessible ───
-- The operator portal now uses this RPC. Confirm it is granted to anon.
-- (This function should already exist from the main schema.sql)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'get_elections_for_tokens'
  ) THEN
    EXECUTE 'GRANT EXECUTE ON FUNCTION get_elections_for_tokens() TO anon';
    RAISE NOTICE 'get_elections_for_tokens() granted to anon';
  ELSE
    RAISE WARNING 'get_elections_for_tokens() function not found! Run schema.sql first.';
  END IF;
END $$;

-- ── Verification ─────────────────────────────────────────────
-- After running, verify:
-- 1. settings table has school_motto, show_bios, show_photos columns
SELECT column_name, data_type, column_default
FROM information_schema.columns
WHERE table_name = 'settings'
ORDER BY ordinal_position;

-- 2. candidates RLS uses is_admin() not auth.role()='authenticated'
SELECT policyname, cmd, qual
FROM pg_policies
WHERE tablename = 'candidates';

-- 3. voters RLS no longer has USING (TRUE)
SELECT policyname, cmd, qual
FROM pg_policies
WHERE tablename = 'voters';
